services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    restart: unless-stopped
    ports:
      - '5673:5673'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  tempo:
    image: grafana/tempo:latest
    restart: unless-stopped
    ports:
      - '4317:4317'
      - '4318:4318'
      - '3100:3100'
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo/tempo-local.yaml
      - tempo_data:/var/tempo
    command: ['--config.file=/etc/tempo/tempo-local.yaml']
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.0.0
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - tempo
    networks:
      - app-network

volumes:
  mongo_data:
  tempo_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
