apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3100
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      search:
        hide: false
      nodeGraph:
        enabled: true